apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kates-home

networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30001
        hostPort: 443
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30002
        hostPort: 15021
        listenAddress: "127.0.0.1"
        protocol: TCP
