apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor
spec:
  selector:
    matchLabels:
      app: temperature-sensor
  template:
    metadata:
      labels:
        app: temperature-sensor
    spec:
      containers:
      - name: temperature-sensor
        image: kates/temperature-sensor
        imagePullPolicy: IfNotPresent 
        env:
          - name: METRICS_PORT
            value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: metrics
            containerPort: 8080
