apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    istio-injection: enabled
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: ke
  namespace: knative-eventing