apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-ingress
spec:
  template:
    spec:
      containers:
        - image: docker.io/deedubs/event-ingress
          imagePullPolicy: IfNotPresent